export const langz = {
  en_US: {
    toolbarTips: {
      bold: 'bold',
      underline: 'underline',
      italic: 'italic',
      strikeThrough: 'strikeThrough',
      title: 'title',
      sub: 'subscript',
      sup: 'superscript',
      quote: 'quote',
      unorderedList: 'unordered list',
      orderedList: 'ordered list',
      task: 'task list',
      codeRow: 'inline code',
      code: 'block-level code',
      link: 'link',
      image: 'image',
      table: 'table',
      mermaid: 'mermaid',
      katex: 'formula',
      revoke: 'revoke',
      next: 'undo revoke',
      save: 'save',
      prettier: 'prettier',
      pageFullscreen: 'fullscreen in page',
      fullscreen: 'fullscreen',
      preview: 'preview',
      previewOnly: 'previewOnly',
      htmlPreview: 'html preview',
      catalog: 'catalog',
      github: 'source code',
    },
    titleItem: {
      h1: 'Lv1 Heading',
      h2: 'Lv2 Heading',
      h3: 'Lv3 Heading',
      h4: 'Lv4 Heading',
      h5: 'Lv5 Heading',
      h6: 'Lv6 Heading',
    },
    imgTitleItem: {
      link: 'Add Img Link',
      upload: 'Upload Img',
      clip2upload: 'Clip Upload',
    },
    linkModalTips: {
      linkTitle: 'Add Link',
      imageTitle: 'Add Image',
      descLabel: 'Desc:',
      descLabelPlaceHolder: 'Enter a description...',
      urlLabel: 'Link:',
      urlLabelPlaceHolder: 'Enter a link...',
      buttonOK: 'OK',
    },
    clipModalTips: {
      title: 'Crop Image',
      buttonUpload: 'Upload',
    },
    copyCode: {
      text: 'Copy',
      successTips: 'Copied!',
      failTips: 'Copy failed!',
    },
    mermaid: {
      flow: 'flow',
      sequence: 'sequence',
      gantt: 'gantt',
      class: 'class',
      state: 'state',
      pie: 'pie',
      relationship: 'relationship',
      journey: 'journey',
    },
    katex: {
      inline: 'inline',
      block: 'block',
    },
    footer: {
      markdownTotal: 'Word Count',
      scrollAuto: 'Scroll Auto',
    },
  },
  fr_FR: {
    toolbarTips: {
      bold: 'gras',
      underline: 'souligné',
      italic: 'italique',
      strikeThrough: 'barré',
      title: 'titre',
      sub: 'indice',
      sup: 'exposant',
      quote: 'citation',
      unorderedList: 'liste non ordonnée',
      orderedList: 'liste ordonnée',
      task: 'liste de tâches',
      codeRow: 'code en ligne',
      code: 'bloc de code',
      link: 'lien',
      image: 'image',
      table: 'tableau',
      mermaid: 'mermaid',
      katex: 'formule',
      revoke: 'annuler',
      next: 'rétablir',
      save: 'enregistrer',
      prettier: 'formater',
      pageFullscreen: 'plein écran dans la page',
      fullscreen: 'plein écran',
      preview: 'aperçu',
      previewOnly: 'aperçu seul',
      htmlPreview: 'aperçu HTML',
      catalog: 'catalogue',
      github: 'code source',
    },
    titleItem: {
      h1: 'Titre Niveau 1',
      h2: 'Titre Niveau 2',
      h3: 'Titre Niveau 3',
      h4: 'Titre Niveau 4',
      h5: 'Titre Niveau 5',
      h6: 'Titre Niveau 6',
    },
    imgTitleItem: {
      link: 'Ajouter lien image',
      upload: 'Téléverser image',
      clip2upload: 'Téléverser à partir du presse-papiers',
    },
    linkModalTips: {
      linkTitle: 'Ajouter un lien',
      imageTitle: 'Ajouter une image',
      descLabel: 'Description :',
      descLabelPlaceHolder: 'Entrez une description...',
      urlLabel: 'Lien :',
      urlLabelPlaceHolder: 'Entrez un lien...',
      buttonOK: 'OK',
    },
    clipModalTips: {
      title: 'Recadrer l\'image',
      buttonUpload: 'Téléverser',
    },
    copyCode: {
      text: 'Copier',
      successTips: 'Copié !',
      failTips: 'Échec de la copie !',
    },
    mermaid: {
      flow: 'flux',
      sequence: 'séquence',
      gantt: 'gantt',
      class: 'classe',
      state: 'état',
      pie: 'camembert',
      relationship: 'relation',
      journey: 'parcours',
    },
    katex: {
      inline: 'en ligne',
      block: 'bloc',
    },
    footer: {
      markdownTotal: 'Nombre de mots',
      scrollAuto: 'Défilement automatique',
    },
  },
}
export const tbars = [
  'bold',
  'underline',
  'italic',
  // 0,
  '-',
  'title',
  'strikeThrough',
  'sub',
  'sup',
  'quote',
  'unorderedList',
  'orderedList',
  'task',
  '-',
  'codeRow',
  'code',
  'link',
  // 'image',
  'table',
  // 'mermaid',
  'katex',
  '-',
  'revoke',
  'next',
  'save',
  '=',
  'pageFullscreen',
  'fullscreen',
  'preview',
  'previewOnly',
  'catalog',
]
